# Generated by Django 5.2.10 on 2026-01-26 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom unique de l'agent", max_length=200, verbose_name="Nom de l'agent")),
                ('description', models.TextField(blank=True, help_text="Description de l'agent et de ses capacités", verbose_name='Description')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Tags pour catégoriser l'agent", size=None, verbose_name='Catégories')),
                ('llm_model', models.CharField(choices=[('azure.gpt-4.1', 'azure.gpt-4.1'), ('azure.gpt-4.1-mini', 'azure.gpt-4.1 Turbo'), ('azure.gpt-4o', 'azure.gpt-4o'), ('azure.gpt-4o-mini', 'azure.gpt-4o Mini'), ('azure.gpt-5.1-turbo', 'azure.gpt-5.1 Turbo')], default='azure.gpt-4.1', help_text="Modèle de langage utilisé par l'agent", max_length=50, verbose_name='Modèle LLM')),
                ('system_prompt', models.TextField(help_text="Instructions système pour l'agent", verbose_name='Prompt Système')),
                ('temperature', models.FloatField(default=0.7, help_text='Contrôle la créativité (0.0 = déterministe, 1.0 = créatif)', verbose_name='Température')),
                ('max_tokens', models.IntegerField(default=2000, help_text='Nombre maximum de tokens dans la réponse', verbose_name='Tokens Max')),
                ('is_active', models.BooleanField(default=True, help_text="L'agent est-il actif et disponible ?", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
