# Generated by Django 5.2.10 on 2026-02-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_llm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('client', 'Client'), ('metier', 'Métier')], default='client', help_text='Client = répond aux questions | Métier = initie la conversation', max_length=10, verbose_name="Type d'agent"),
        ),
        migrations.AddField(
            model_name='agent',
            name='first_prompt',
            field=models.TextField(blank=True, help_text='Message initial pour les agents métier (obligatoire si type = métier)', null=True, verbose_name='Premier prompt'),
        ),
    ]
