# Generated by Django 5.2.11 on 2026-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_agent_type_agent_first_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('azure.gpt-4o', 'litellm Azure GPT-4o'), ('azure.gpt-4o-mini', 'litellm Azure GPT-4o Mini')], help_text="Modèle de langage utilisé par l'agent", max_length=50, verbose_name='Modèle LLM'),
        ),
    ]
