# Generated by Django 5.2.10 on 2026-01-26 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Titre de la conversation (généré automatiquement)', max_length=255, verbose_name='Titre')),
                ('conversation_type', models.CharField(choices=[('user', 'Utilisateur-Agent'), ('auto', 'Agent-Agent (Auto-Chat)')], default='user', max_length=10, verbose_name='Type de conversation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agents', models.ManyToManyField(related_name='conversations', to='agents.agent', verbose_name='Agents impliqués')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('human', 'Humain'), ('ai', 'IA'), ('system', 'Système')], max_length=10, verbose_name='Rôle')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_auto_chat', models.BooleanField(default=False, help_text='Message généré par le mode Auto-Chat', verbose_name='Auto-Chat')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Informations supplémentaires (tokens, durée, etc.)', verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='agents.agent', verbose_name='Agent (si AI)')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
